<?php

declare(strict_types=1);

return [
    [
        "name" => "_",
        "max_clients" => 0,
        "talk_power" => 0,
        "spacer" => true,
        "center" => false,
    ],
    [
        "name" => "G A M E S",
        "max_clients" => 0,
        "talk_power" => 0,
        "spacer" => false,
        "center" => true,
    ],
    [
        "name" => "_",
        "max_clients" => 0,
        "talk_power" => 0,
        "spacer" => true,
        "center" => false,
    ],
    [
        "name" => "Channel I",
        "max_clients" => -1,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Channel II",
        "max_clients" => -1,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Channel III",
        "max_clients" => -1,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Channel IV",
        "max_clients" => -1,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Channel V",
        "max_clients" => -1,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "_",
        "max_clients" => 0,
        "talk_power" => 0,
        "spacer" => true,
        "center" => false,
    ],
    [
        "name" => "O T H E R S",
        "max_clients" => 0,
        "talk_power" => 0,
        "spacer" => false,
        "center" => true,
    ],
    [
        "name" => "Random I",
        "max_clients" => -1,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Random II",
        "max_clients" => -1,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Random III",
        "max_clients" => -1,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "_",
        "max_clients" => 0,
        "talk_power" => 0,
        "spacer" => true,
        "center" => false,
    ],
    [
        "name" => "L I M I T E D",
        "max_clients" => 0,
        "talk_power" => 0,
        "spacer" => false,
        "center" => true,
    ],
    [
        "name" => "Channel 2 People",
        "max_clients" => 2,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Channel 3 People",
        "max_clients" => 3,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Channel 4 People",
        "max_clients" => 4,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Channel 5 People",
        "max_clients" => 5,
        "talk_power" => 0,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "_",
        "max_clients" => 0,
        "talk_power" => 0,
        "spacer" => true,
        "center" => false,
    ],
    [
        "name" => "A F K",
        "max_clients" => 0,
        "talk_power" => 0,
        "spacer" => false,
        "center" => true,
    ],
    [
        "name" => "Long",
        "max_clients" => -1,
        "talk_power" => 1337,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Short",
        "max_clients" => -1,
        "talk_power" => 1337,
        "spacer" => false,
        "center" => false,
    ],
    [
        "name" => "Work",
        "max_clients" => -1,
        "talk_power" => 1337,
        "spacer" => false,
        "center" => false,
    ],
];
